name: Linter and tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  wmpsg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.15.3



